import React, { useState } from 'react';
import DiffSlot from '../components/DiffSlot';
import Head from 'next/head';
import newjson from '../data/new.json'

const Home = () => {
  const [champions] = useState(newjson);

  const filteredChampions = Object.entries(champions).filter(([championName, patches]) => {
    return patches.Patches.hasOwnProperty("13.3");
  });

  return (
    <>
      <Head>
        <title>LOLDIFF</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="mt-8 mb-8 max-w-screen-md mx-auto flex items-center justify-between">
        <h1 className="text-6xl font-bold text-white text-center">LOL<span className='text-orange-900'>diff</span></h1>
        <h2 className='flex flex-row'><pre>Patch: </pre> 13.3</h2>
      </header>



      <main className="flex flex-row flex-wrap justify-center">
        {filteredChampions.map(([championName, patches], i) => (
          <DiffSlot key={i} championName={championName} patches={patches.Patches} />
        ))}
      </main>
    </>
  );
};

export default Home;
